version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: inventario_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: falcon_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: